name: Build Site (PR check)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs: 
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install deps
      run: |
        sudo apt-get -y update && \
        sudo apt-get -y install python3-tornado python3-yaml python3-markdown python3-dateutil python3-nbconvert pandoc

    - name: Build site
      run: make clean && make build

    # No deploy in PR validation workflow
